---
apiVersion: v1
kind: Service
metadata:
  name: app-service-{{ .Values.environment }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.pods.label }}-{{ .Values.environment }}
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 5000