---
apiVersion: v1
kind: Service
metadata:
  name: python-v1-public
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.pods.label }}
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 5000