replicaCount: 3

image:
  repository: ghcr.io/cortiz2024/demo_app/demo_app
  pullPolicy: IfNotPresent
  tag: "v0.1.0"

pods:
  label: python-app

service:
  type: ClusterIP
  port: 5000

secret:
  name: dockerconfigjson-github-com
  encode: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZMjl5ZEdsNk1qQXlORHBuYUhCZlJtOXFaM3BOUjJkMFdqVlhWM294U2s1ak9IUnZSVWRhUVRkeFNFSnpNR1ZJVkU1cSJ9fX0=