apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../base/charts

helmCharts:
- name: python-app
  releaseName: python-app-dev
  valuesFile: ./patch-values.yaml