apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../base/charts

helmCharts:
- name: python-apps
  releaseName: pyhton-apps-dev
  valuesFile: ./patch-values.yaml