apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: net-apps-dev
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: main-project
  source:
    path: overlays/dev/python-apps
    repoURL: git@github.com:cortiz2024/test_image.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true