namespace: argocd
environment: dev
projects:
  projectOne:
    name: project-one
    sourceRepos:
      - '!ssh://git@GITHUB.com:infrastructure-services/test'
    destinations:
      - namespace: '*'
        server: 'https://kubernetes.default.svc'
  projectTwo:
    name: project-two
  projectThree:
    name: project-three
