environment: dev
namespace: argocd
projects:
  projectOne:
    name: project-one
    sourceRepos:
      - '!ssh://git@GITHUB.com:infrastructure-services/test'
      - '!https://gitlab.com/group/**'
      - '*'
    destinations:
      - namespace: '*'
        server: 'https://kubernetes.default.svc'
