apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-two-test
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - '!ssh://git@GITHUB.com:infrastructure-services/test'