apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../base/charts

helmCharts:
- name: projects
  releaseName: projects-prod
  valuesFile: ./patch-values.yaml