apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: DemoProject
  namespace: argocd
spec:
  sourceRepos:
    # Do not use this repo in argoproj
    - '!ssh://git@GITHUB.com:infrastructure-services/test'
    # Nor any Gitlab repo under group/ 
    - '!https://gitlab.com/group/**'
    # Any other repo is fine though
    - '*'
  destinations:
  # Do not allow any app to be installed in `kube-system`  
  - namespace: '!kube-system'
    server: '*'
  # Or any cluster that has a URL of `unknown-*`   
  - namespace: '*'
    server: '!https://unknown-*'
  # Specifying another namespace or server is fine.
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
