namespace: argocd
project:
  name:
    prefix: main-project

spec:
  sourceRepos:
    - '!ssh://git@GITHUB.com:infrastructure-services/test'
    - '!https://gitlab.com/group/**'
    - '*'
  destinations:
    - namespace: '!kube-system'
      server: '*'
    - namespace: '*'
      server: '!https://unknown-*'
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    group: '*'
    kind: '*'

applications:
  projects:
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    path: overlays/dev/projects
    repoURL: git@github.com:cortiz2024/test_image.git
    targetRevision: HEAD
  apps:
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    path: overlays/dev/apps-of-apps
    repoURL: git@github.com:cortiz2024/test_image.git
    targetRevision: HEAD

applicationsprod:
  projects:
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    path: overlays/production/projects
    repoURL: git@github.com:cortiz2024/test_image.git
    targetRevision: HEAD
  apps:
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    path: overlays/production/apps-of-apps
    repoURL: git@github.com:cortiz2024/test_image.git
    targetRevision: HEAD

repoSecret:
  name: main-private-repo-secret
  stringData:
    type: git
    url: git@github.com:cortiz2024/test_image.git

registrySecret:
  name: main-private-registry-secret
  stringData:
    type: helm
    url: demodevacr.azurecr.io
    username: 00000000-0000-0000-0000-000000000000
    password: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlNXUVk6VFFVSjpWSEZIOkFETjU6T1JTTzpIRks1OlZDWEg6NTNPTjpBTkNUOjJQMjI6MzRBQjpUVzVPIn0.eyJqdGkiOiIxZDliNzAzYi0zMTljLTQ0ZWItOTY5Yy01M2JjOWE1MmJhM2MiLCJzdWIiOiJjbG91ZF91c2VyX3BfMzlhZGYyMDdAcmVhbGhhbmRzb25sYWJzLmNvbSIsIm5iZiI6MTcwNTk0MTQ0MywiZXhwIjoxNzA1OTUzMTQzLCJpYXQiOjE3MDU5NDE0NDMsImlzcyI6IkF6dXJlIENvbnRhaW5lciBSZWdpc3RyeSIsImF1ZCI6ImRlbW9kZXZhY3IuYXp1cmVjci5pbyIsInZlcnNpb24iOiIxLjAiLCJyaWQiOiJjZWMxZTBiNzdmOTY0YzhlYjllY2U3YzYzNGU4ZTBhYSIsImdyYW50X3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwiYXBwaWQiOiIwNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDYiLCJ0ZW5hbnQiOiI4NGYxZTRlYS04NTU0LTQzZTEtODcwOS1mMGI4NTg5ZWExMTgiLCJwZXJtaXNzaW9ucyI6eyJBY3Rpb25zIjpbInJlYWQiLCJ3cml0ZSIsImRlbGV0ZSIsIm1ldGFkYXRhL3JlYWQiLCJtZXRhZGF0YS93cml0ZSIsImRlbGV0ZWQvcmVhZCIsImRlbGV0ZWQvcmVzdG9yZS9hY3Rpb24iXSwiTm90QWN0aW9ucyI6bnVsbH0sInJvbGVzIjpbXX0.C2BgR70_dq8LAGmYw6yU4_d01q9XJEtTYrbqdNZrsyyX1XFszOLSJC4lV7m2NDWvSbfXhXV85n_N7Zkq8u6NrdzNSCERVrXjeIXChlvWTcJ3HvZ11vrybBmc7opeAqJXoSpwBLNOOXMjk-cm-KkBToMNMXkejvHy2Vq_onECzzVNfd3RY2BM_xFIBOa9VmTYvPATLqcjVLBiksISZ9zpZLpFgEs40PFV1qx0AfRmVVLcJOuA9mGpAxOvsahRVcbXCa6Tg_KeWYmOtCXsMxNQ3gdVX1AR4mo6cnY2QdvzpqoG6iOe0x528Av2V8EH4pvNxtM8jM6VX6X4Lz25g-Q0gg