namespace: argocd
project:
  name:
    prefix: main-project

spec:
  sourceRepos:
    - '!ssh://git@GITHUB.com:infrastructure-services/test'
    - '!https://gitlab.com/group/**'
    - '*'
  destinations:
    - namespace: '!kube-system'
      server: '*'
    - namespace: '*'
      server: '!https://unknown-*'
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    group: '*'
    kind: '*'

applications:
  projects:
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    path: overlays/dev/projects
    repoURL: git@github.com:cortiz2024/test_image.git
    targetRevision: HEAD
  apps:
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    path: overlays/dev/apps-of-apps
    repoURL: git@github.com:cortiz2024/test_image.git
    targetRevision: HEAD

applicationsprod:
  projects:
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    path: overlays/production/projects
    repoURL: git@github.com:cortiz2024/test_image.git
    targetRevision: HEAD
  apps:
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    path: overlays/production/apps-of-apps
    repoURL: git@github.com:cortiz2024/test_image.git
    targetRevision: HEAD

repoSecret:
  name: main-private-repo-secret
  stringData:
    type: git
    url: git@github.com:cortiz2024/test_image.git

registrySecret:
  name: main-private-registry-secret
  stringData:
    type: helm
    url: aksdevacr1.azurecr.io
    username: 00000000-0000-0000-0000-000000000000
    password: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlNXUVk6VFFVSjpWSEZIOkFETjU6T1JTTzpIRks1OlZDWEg6NTNPTjpBTkNUOjJQMjI6MzRBQjpUVzVPIn0.eyJqdGkiOiI5MDE1NjQwZS01N2Y1LTQxZmQtYmI2My1hNWJjNmRiYjExYmQiLCJzdWIiOiJjbG91ZF91c2VyX3BfNDNmNWU0ZDFAcmVhbGhhbmRzb25sYWJzLmNvbSIsIm5iZiI6MTcwNTk2MTc5MywiZXhwIjoxNzA1OTczNDkzLCJpYXQiOjE3MDU5NjE3OTMsImlzcyI6IkF6dXJlIENvbnRhaW5lciBSZWdpc3RyeSIsImF1ZCI6ImFrc2RldmFjcjEuYXp1cmVjci5pbyIsInZlcnNpb24iOiIxLjAiLCJyaWQiOiI4ZTYyZjhlYTQxMjU0MThjYTdjMjBjODQxNTQyYWI4NyIsImdyYW50X3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwiYXBwaWQiOiIwNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDYiLCJ0ZW5hbnQiOiI4NGYxZTRlYS04NTU0LTQzZTEtODcwOS1mMGI4NTg5ZWExMTgiLCJwZXJtaXNzaW9ucyI6eyJBY3Rpb25zIjpbInJlYWQiLCJ3cml0ZSIsImRlbGV0ZSIsIm1ldGFkYXRhL3JlYWQiLCJtZXRhZGF0YS93cml0ZSIsImRlbGV0ZWQvcmVhZCIsImRlbGV0ZWQvcmVzdG9yZS9hY3Rpb24iXSwiTm90QWN0aW9ucyI6bnVsbH0sInJvbGVzIjpbXX0.r23IrKU_4yxzeCeYG6Yy2q51WhiivCVhvoOVw-5aMtSG7fQ08VbFPh5VOIUj_ebnUjezFeBAJpXKrX8eZt8hyoHOK76QvDEo-E7Eg-TbwhiGPwUO4Rh5I-Dw9ZWG_tji80Y_iTVbhmFjJBak8EgDDcVplDS9Z9qt71VoGHVv1WgGXrCtbRPiL2qWyjeeuB1XKXgxra9k0C15ojKyd7wVmMGYUFCxyfEZDNV5GWpiOlPrRxsL4NABUUSCWwZzFumRmmGeN4XJtMexZmHTURpaM_XLG7kaFeh3RWinHOOsaGceblyiIYFrKVC4_g8zl_oA6POw5AbueF9_jyBH-KZgOw