environment: test

appOne:
  appName: app-of-apps-n
  projectName: project_n
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  destination:
    server: https://kubernetes.default.svc
  source:
    path: overlays/test/app
    repoURL: git@github.com:cortiz2024/test_image.git
    targetRevision: HEAD

secret:
  name: test-private-repo
  labels:
    argocd.argoproj.io/secret-type: repository
  stringData:
    type: git
    url: git@github.com:user/repo.git