apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-{{ .Values.environment }}
  labels:
    app: {{ .Values.pods.label }}-{{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.pods.label }}-{{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.pods.label }}-{{ .Values.environment }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
      imagePullSecrets:
      - name: {{ .Values.secret.name }}-{{ .Values.environment }}