kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: {{ .Values.secret.name }}-{{ .Values.environment }}
  labels:
    app: {{ .Values.pods.label }}-{{ .Values.environment }}
data:
  .dockerconfigjson: {{ .Values.secret.encode }}