namespace: argocd

project:
  name: main-project

appProject:
  sourceRepos:
    - '!ssh://git@GITHUB.com:infrastructure-services/test'
    - '!https://gitlab.com/group/**'
    - '*'
  destinations:
    - namespace: '!kube-system'
      server: '*'
    - namespace: '*'
      server: '!https://unknown-*'
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    group: '*'
    kind: '*'

application:
  name: app-of-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  destination:
    server: https://kubernetes.default.svc
  source:
    path: charts/applications
    repoURL: git@github.com:cortiz2024/test_image.git
    targetRevision: HEAD

secret:
  name: private-repo
  labels:
    argocd.argoproj.io/secret-type: repository
  stringData:
    type: git
    url: git@github.com:cortiz2024/test_image.git
