apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../base/charts

helmCharts:
- name: applications
  releaseName: applications-prod
  valuesFile: ./patch-values.yaml