kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ .Values.pods.label }}
data:
  .dockerconfigjson: {{ .Values.secret.encode }}
