appOne:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  destination:
    server: https://kubernetes.default.svc

secret:
  name: test-private-repo
  labels:
    argocd.argoproj.io/secret-type: repository
  stringData:
    type: git
    url: git@github.com:user/repo.git